
import java.awt.Label;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class game extends javax.swing.JFrame {

    ImageIcon Imagem = new ImageIcon(getClass().getResource("tesourairada.webp"));
    JLabel label = new JLabel(Imagem);

    private int escolhaJogador;
    private int pD = 1;
    private int pV = 1;

    public game() {
        initComponents();
        add(label);
    }

    public int escolherPc() {
        return ((int) (1 + Math.random() * 3));
    }

    public void darResultado() {
        if (escolhaJogador == escolherPc()) {
            showman.setText("EMPATE");
        } else if ((escolhaJogador == 1 && escolherPc() == 3)
                || (escolhaJogador == 2 && escolherPc() == 1)
                || (escolhaJogador == 3 && escolherPc() == 2)) {
            showman.setText("DERROTA");
            scorePc.setText(Integer.toString(pD++));
        } else {
            showman.setText("VITÓRIA");
            scorePlayer.setText(Integer.toString(pV++));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tesouraBotao = new javax.swing.JButton();
        pedraBotao = new javax.swing.JButton();
        papelBotao = new javax.swing.JButton();
        showman = new java.awt.Label();
        scorePc = new java.awt.Label();
        scorePlayer = new java.awt.Label();
        vs = new java.awt.Label();
        pc = new java.awt.Label();
        pc1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("JOKENPO - PRO EDITION");

        tesouraBotao.setBackground(new java.awt.Color(255, 255, 255));
        tesouraBotao.setForeground(new java.awt.Color(255, 255, 255));
        tesouraBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesoura.png"))); // NOI18N
        tesouraBotao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tesouraBotao.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        tesouraBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tesouraBotaoActionPerformed(evt);
            }
        });

        pedraBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pedra.png"))); // NOI18N
        pedraBotao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pedraBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedraBotaoActionPerformed(evt);
            }
        });

        papelBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/papel.png"))); // NOI18N
        papelBotao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        papelBotao.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        papelBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papelBotaoActionPerformed(evt);
            }
        });

        showman.setAlignment(java.awt.Label.CENTER);
        showman.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N

        scorePc.setAlignment(java.awt.Label.CENTER);
        scorePc.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        scorePc.setText("0");

        scorePlayer.setAlignment(java.awt.Label.CENTER);
        scorePlayer.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        scorePlayer.setText("0");

        vs.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        vs.setText("VS");

        pc.setAlignment(java.awt.Label.CENTER);
        pc.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        pc.setText("VOCÊ");

        pc1.setAlignment(java.awt.Label.CENTER);
        pc1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        pc1.setText("PC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(168, 168, 168))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(pedraBotao)
                .addGap(111, 111, 111)
                .addComponent(tesouraBotao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(papelBotao)
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showman, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(scorePc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(vs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(scorePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(pc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scorePc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scorePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(showman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pedraBotao)
                    .addComponent(papelBotao)
                    .addComponent(tesouraBotao))
                .addGap(149, 149, 149))
        );

        showman.getAccessibleContext().setAccessibleName("showman");
        vs.getAccessibleContext().setAccessibleName("label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tesouraBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tesouraBotaoActionPerformed
        this.escolhaJogador = 1;
        darResultado();
    }//GEN-LAST:event_tesouraBotaoActionPerformed

    private void pedraBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedraBotaoActionPerformed
        darResultado();
    }//GEN-LAST:event_pedraBotaoActionPerformed

    private void papelBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papelBotaoActionPerformed
        this.escolhaJogador = 3;
        darResultado();
    }//GEN-LAST:event_papelBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton papelBotao;
    private java.awt.Label pc;
    private java.awt.Label pc1;
    private javax.swing.JButton pedraBotao;
    private java.awt.Label scorePc;
    private java.awt.Label scorePlayer;
    private java.awt.Label showman;
    private javax.swing.JButton tesouraBotao;
    private java.awt.Label vs;
    // End of variables declaration//GEN-END:variables

    public JLabel getLabel() {
        return label;
    }

    public void setLabel(JLabel label) {
        this.label = label;
    }

    public int getEscolhaJogador() {
        return escolhaJogador;
    }

    public void setEscolhaJogador(int escolhaJogador) {
        this.escolhaJogador = escolhaJogador;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JButton getPapelBotao() {
        return papelBotao;
    }

    public void setPapelBotao(JButton papelBotao) {
        this.papelBotao = papelBotao;
    }

    public JButton getPedraBotao() {
        return pedraBotao;
    }

    public void setPedraBotao(JButton pedraBotao) {
        this.pedraBotao = pedraBotao;
    }

    public Label getScorePc() {
        return scorePc;
    }

    public void setScorePc(Label scorePc) {
        this.scorePc = scorePc;
    }

    public Label getScorePlayer() {
        return scorePlayer;
    }

    public void setScorePlayer(Label scorePlayer) {
        this.scorePlayer = scorePlayer;
    }

    public Label getShowman() {
        return showman;
    }

    public void setShowman(Label showman) {
        this.showman = showman;
    }

    public JButton getTesouraBotao() {
        return tesouraBotao;
    }

    public void setTesouraBotao(JButton tesouraBotao) {
        this.tesouraBotao = tesouraBotao;
    }

    public Label getVs() {
        return vs;
    }

    public void setVs(Label vs) {
        this.vs = vs;
    }

}
